Achievement 2/Exercise2.8/src/apps/recipes/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView, add_recipe, home_view, search_view, chart_view

app_name = 'recipe'

urlpatterns = [
    path('', home_view, name='home'), 
    path('list/', RecipeListView.as_view(), name='recipe_list'), 
    path('<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),  
    path('add/', add_recipe, name='add_recipe'),
    path('search/', search_view, name='search'),
    path('charts/', chart_view, name='charts'),
]

Achievement 2/Exercise2.8/src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.recipes.views import home_view
from apps.auth.views import login_view, profile_view, logout_view, logout_success_view
from apps.core.views import about_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('', include('apps.recipes.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('login/', login_view, name='login'),
    path('profile/', profile_view, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('logout-success/', logout_success_view, name='logout_success'),
    path('about/', about_view, name='about')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Achievement 2/Exercise2.8/src/apps/core/models.py
from django.db import models

# Create your models here.

Achievement 2/Exercise2.8/src/apps/recipes/models.py
from django.db import models


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=55)
    ingredients = models.CharField(max_length=255)
    cooking_time = models.IntegerField()
    difficulty = models.CharField(max_length=20, editable=False)
    directions = models.TextField(max_length=2000, default="")
    image = models.ImageField(upload_to="recipe_images", default="no_picture.jpg")

    def save(self, *args, **kwargs):
        self.calculate_difficulty()
        super().save(*args, **kwargs)

    def return_ingredients_as_list(self):
        return [ingredient.strip() for ingredient in self.ingredients.split(",")]

    def calculate_difficulty(self):
        cooking_time = int(self.cooking_time)
        num_ingredients = len(self.return_ingredients_as_list())

        if cooking_time < 10 and num_ingredients < 4:
            difficulty = "Easy"
        elif cooking_time < 10 and num_ingredients >= 4:
            difficulty = "Medium"
        elif cooking_time >= 10 and num_ingredients < 4:
            difficulty = "Intermediate"
        else:
            difficulty = "Hard"

        self.difficulty = difficulty

    def __str__(self):
        return f"Recipe ID: {self.id} - {self.name}"

Achievement 2/Exercise2.8/src/apps/recipes/forms.py
from django import forms                        # modelForms are directly tied to Django models.
from .models import Recipe
from django.forms import widgets
from markdownx.fields import MarkdownxFormField


class RecipeForm(forms.ModelForm):
    directions = MarkdownxFormField()
    
    # meta information
    class Meta:
        model = Recipe
        fields = ['name', 'ingredients', 'cooking_time', 'directions', 'image']
      

SEARCHING_BY_CHOICES = (
    ('name', 'Name'),
    ('ingredient', "Ingredient"),    
    ('cooking_time', "Cooking Time"),  
    ('difficulty', 'Difficulty')
)
class RecipeSearch(forms.Form):
    searching_by = forms.ChoiceField(choices=SEARCHING_BY_CHOICES)
    search_term = forms.CharField(max_length=120)

Achievement 2/Exercise2.8/src/apps/core/views.py
from django.shortcuts import render

def about_view(request):
    
    return render(request, 'about_me.html')

Achievement 2/Exercise2.8/src/apps/recipes/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import Recipe
from .forms import RecipeForm, RecipeSearch
from .utils import get_chart
import random
import pandas as pd
import string



def home_view(request):
    recipes = Recipe.objects.all()
    if recipes:
        random_recipe = random.choice(recipes)
        context = {'recipe': random_recipe}
    else:
        context = {'no_recipes': True}
    return render(request, 'recipes/recipes_home.html', context)

class RecipeListView(ListView):
    template_name = 'recipes/recipe_list.html'
    paginate_by = 3

    def get(self, request):
        recipes = Recipe.objects.all().order_by('name')
        page_obj = paginate_queryset(request, recipes, self.paginate_by)
        context = {
            'recipes': page_obj.object_list,
            'page_obj': page_obj,
        }
        return render(request, self.template_name, context)

class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'recipes/recipe_detail.html'
    context_object_name = 'recipe'

@login_required
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.save()
            return redirect('recipe:recipe_list')
    else:
        form = RecipeForm()
    
    return render(request, 'recipes/add_recipe.html', {'form': form})

def search_view(request):
    results = []
    form = RecipeSearch(request.POST or None)
    df = None                                                       # df dataframe
    page_number = request.GET.get('page') or 1                      # Get page number from query params

    if request.method == 'POST' and form.is_valid():
        searching_by = request.POST.get('searching_by')
        search_term = request.POST.get('search_term')

    else:
        searching_by = request.GET.get('searching_by')
        search_term = request.GET.get('search_term')

    print(search_term, searching_by, page_number)

    # Dynamically filter based on what the user is searching by
    if searching_by == 'name':  
        results = Recipe.objects.filter(name__icontains=search_term).order_by('name')
    elif searching_by == 'ingredient':  
        results = Recipe.objects.filter(ingredients__icontains=search_term).order_by('name')
    elif searching_by == 'difficulty':  
        results = Recipe.objects.filter(difficulty__iexact=search_term).order_by('name')
    elif searching_by == 'cooking_time':  
        try:
            cooking_time = int(search_term)
            results = Recipe.objects.filter(cooking_time=cooking_time).order_by('name')
        except ValueError:
            results = []  

    
    # Paginate results
    paginator = Paginator(results, 3)  
    page_obj = paginator.get_page(page_number)
    
    print(paginator, page_obj)

    if results:
        df = pd.DataFrame(results.values())    

        # DataFrame transformations
        df['name'] = df.apply(make_clickable_name, axis=1)
        df['cooking_time'] = df['cooking_time'].astype(str) + ' min'  # Format cooking time
        
        # Drop columns you don't want to display
        df = df[['name', 'ingredients', 'cooking_time', 'difficulty']]

        # Convert to HTML table with styling options
        df = df.to_html( 
            classes='table table-striped table-hover bg-transparent text-light',
            index=False,  # Hide the index column
            justify='start',  # Center-align the table content
            border=0,
            render_links=True,  # Enable clickable links if you have URLs
            escape=False  # Avoid escaping HTML (e.g., if you want to render images or links)
        )
    
    context = {
        'form': form,
        'results': page_obj.object_list,
        'page_obj': page_obj,
        'df':df,
        'search_term': search_term,
        'searching_by': searching_by,
    }

    return render(request, 'recipes/search.html', context)

def chart_view(request):
    chart = None
    df = None
    qs = Recipe.objects.all().values()
    
    if qs:                
        pie_chart = get_chart('PC', qs)
        bar_chart = get_chart('BC', qs)
        line_chart= get_chart('LC', qs)
    
    context = {
        'pie_chart': pie_chart,
        'bar_chart': bar_chart,
        'line_chart': line_chart
    }
    return render(request, 'recipes/recipe_charts.html', context)

# # Helper functions
# create clickable links for the recipe name
def make_clickable_name(row):
    url = reverse('recipe:recipe_detail', args=[row['id']])
    return f'<a href="{url}">{string.capwords(row["name"])}</a>'

# pagination
def paginate_queryset(request, queryset, paginate_by):
    paginator = Paginator(queryset, paginate_by)
    page_number = request.GET.get('page') or 1
    page_obj = paginator.get_page(page_number)
    return page_obj

Achievement 2/Exercise2.8/src/apps/core/templates/about_me.html
{% extends "base.html" %}
{% load static %}
{% block title %}About Me{% endblock %}

{% block content %}
    <div class="row d-flex flex-row justify-content-center mt-5 pt-5">
        
        <div class="col-12 col-md-auto   d-flex flex-column justify-content-center">
            <img src="{% static 'img/David_square.jpg' %}" class="img-fluid rounded-circle img_aboutme "  alt="picture of david">
        </div>
        <div class="col-12 col-md-auto  px-3 d-flex flex-column justify-content-center">
            <h1 class="display-3 mt-5 mb-4 ps-sm-3">Hi, I'm David</h1>
            <p class="lead ps-sm-3">
                I am the developer of this app.<br>
                Glad you found it and hope you like it.<br>
            </p>
            <p class="lead ps-sm-3">
                If you want to get in touch or just have a look at what else I have built, check out...
            </p>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"> 
                    <a href="https://davidjuliangit.github.io/Portfolio-Website/" target="_blank" class="link">
                        <i class="bi bi-briefcase me-1"></i>Portfolio 
                    </a>
                </li>
                <li class="list-group-item"> 
                    <a href="https://github.com/DavidJulianGit" target="_blank">
                        <i class="bi bi-github me-1"></i>GitHub
                    </a>
                </li>
                <li class="list-group-item"> 
                    <a href="https://www.linkedin.com/in/david-schindler-51ab37149/" target="_blank">
                        <i class="bi bi-linkedin me-1"></i>LinkedIn
                    </a>
                </li>
            </ul>
        </div>
    </div>
        
{% endblock %} 

Achievement 2/Exercise2.8/src/apps/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
</head>
<body class="d-flex flex-column min-vh-100 pt-5"> 

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
        <div class="container"> 
            <a class="navbar-brand fs-3" href="{% url 'recipe:home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto fs-5" >
                    <!-- Check if the user is logged in -->
                    {% if user.is_authenticated %}
                        <!-- If logged in -->
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link text-light" href="{% url 'recipe:search' %}">
                                <span class="m-0 p-0" ></span>
                                <i class="bi bi-search me-1"></i>Search 
                                </span>
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link text-light" href="{% url 'recipe:charts' %}">
                                <span class="m-0 p-0" ></span>
                                <i class="bi bi-bar-chart-line me-1"></i>Visualization
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link text-light" href="{% url 'profile' %}">
                                <span class="m-0 p-0" >
                                    <i class="bi bi-person me-1"></i>Profile 
                                </span>
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a href="#" class="nav-link text-light" data-bs-toggle="modal" data-bs-target="#addRecipeModal">
                                <span class="m-0 p-0">
                                    <i class="bi bi-plus-circle me-1"></i>Add Recipe
                                </span>
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link text-light" href="{% url 'recipe:recipe_list' %}">
                                <span class="m-0 p-0" ></span>
                                <i class="bi bi-card-text me-1"></i>All Recipes 
                                </span>
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link text-light" href="{% url 'logout' %}">
                                <span class="m-0 p-0" >
                                    <i class="bi bi-box-arrow-right me-1"></i>Logout 
                                </span>
                            </a> 
                        </li>

                         <!-- If not logged in -->
                        {% else %}
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link disabled" href="{% url 'recipe:search' %}">
                                <span class="m-0 p-0" ></span>
                                <i class="bi bi-search me-1"></i>Search 
                                </span>
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link disabled" href="{% url 'recipe:charts' %}">
                                <span class="m-0 p-0" ></span>
                                <i class="bi bi-bar-chart-line me-1"></i>Visualization
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link disabled" href="{% url 'profile' %}">
                                <span class="m-0 p-0" >
                                    <i class="bi bi-person me-1"></i>Profile 
                                </span>
                            </a>
                        </li>

                        <li class="nav-item d-flex align-items-center mx-1">
                            <a href="#" class="nav-link disabled" data-bs-toggle="modal" data-bs-target="#addRecipeModal">
                                <span class="m-0 p-0">
                                    <i class="bi bi-plus-circle me-1"></i>Add Recipe
                                </span>
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link text-light" href="{% url 'recipe:recipe_list' %}">
                                <span class="m-0 p-0" ></span>
                                <i class="bi bi-card-text me-1"></i>All Recipes 
                                </span>
                            </a>
                        </li>
                        <li class="nav-item d-flex align-items-center mx-1">
                            <a class="nav-link text-light" href="{% url 'login' %}">
                                <span class="m-0 p-0" ></span>
                                    <i class="bi bi-box-arrow-in-right me-1"></i>Login 
                                </span>
                            </a>  
                        </li>   
                    {% endif %}
               </ul>
            </div>
        </div>
    </nav>
    

    <!-- Main content -->
    <main class="flex-grow-1 container my-4"> 
        {% block content %}{% endblock %}
    </main>

    <!-- Pagination -->
    <div class="container h-100 d-flex flex-row justify-content-center ">
        {% block pagination %}
        {% endblock %}
    </div>
   
    <!-- Footer -->
    <footer class="bg-primary text-center text-white py-3 mt-auto"> 
        <div class="container">
            <p class="mb-0"> 2024 Recipe App <br/> &copy;<a href="{% url 'about' %}" class="link-light link-underline-light link-offset-2 link-underline-opacity-50 link-opacity-50-hover ms-1">David Schindler</a></p>
        </div>
    </footer>

    <!-- Include the Add Recipe modal globally -->
    {% include "recipes/add_recipe_modal.html" %}

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Simple MDE-->
    <script src="{% static 'js/simplemde.js' %}"></script>
</body>
</html>

Achievement 2/Exercise2.8/src/apps/recipes/templates/recipes/add_recipe.html
{% extends "base.html" %}

{% block title %}Add Recipe{% endblock %}
{% include 'add_recipe_modal.html' %}

{% block content %}



{% endblock %}

Achievement 2/Exercise2.8/src/apps/recipes/templates/recipes/add_recipe_modal.html
<!-- Add Recipe Modal -->
<div class="modal fade" id="addRecipeModal" tabindex="-1" data-bs-backdrop="static" aria-labelledby="addRecipeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addRecipeModalLabel">Add a New Recipe</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{% url 'recipe:add_recipe' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="mb-3">
                        <label for="id_name" class="form-label">Recipe Name</label>
                        <input type="text" class="form-control" id="id_name" name="name" autocomplete="off" placeholder="Enter recipe name">
                    </div>

                    <div class="mb-3">
                        <label for="id_ingredients" class="form-label">Ingredients</label>
                        <input type="text" class="form-control" id="id_ingredients" name="ingredients" placeholder="Enter ingredients">
                    </div>

                    <div class="mb-3">
                        <label for="id_cooking_time" class="form-label">Cooking Time (in minutes)</label>
                        <input type="number" class="form-control" id="id_cooking_time" name="cooking_time" placeholder="Enter cooking time">
                    </div>

                    <div class="mb-3">
                        <label for="id_directions" class="form-label">Directions</label>
                        <textarea class="form-control markdown-editor" id="id_directions" name="directions" rows="5" placeholder="Enter directions"></textarea>
                        {{ form.directions }}
                    </div>

                    <div class="mb-3">
                        <label for="id_image" class="form-label">Upload Image</label>
                        <input type="file" class="form-control" id="id_image" name="image">
                    </div>

                    <button type="submit" class="btn btn-primary">Add Recipe</button>
                </form>
            </div>
        </div>
    </div>
</div>

Achievement 2/Exercise2.8/src/apps/recipes/templates/recipes/pagination.html
{% block pagination %}
    
    <div class="pagination-container">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1{% if search_term %}&search_term={{ search_term }}{% endif %}{% if searching_by %}&searching_by={{ searching_by }}{% endif %}" aria-label="First">
                        <span aria-hidden="true"><i class="bi bi-chevron-double-left"></i></span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if search_term %}&search_term={{ search_term }}{% endif %}{% if searching_by %}&searching_by={{ searching_by }}{% endif %}" aria-label="Previous">
                        <span aria-hidden="true"><i class="bi bi-chevron-left"></i></span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link" aria-hidden="true"><i class="bi bi-chevron-double-left"></i></span>
                </li>
                <li class="page-item disabled">
                    <span class="page-link" aria-hidden="true"><i class="bi bi-chevron-left"></i></span>
                </li>
            {% endif %}
    
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}{% if search_term %}&search_term={{ search_term }}{% endif %}{% if searching_by %}&searching_by={{ searching_by }}{% endif %}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
    
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if search_term %}&search_term={{ search_term }}{% endif %}{% if searching_by %}&searching_by={{ searching_by }}{% endif %}" aria-label="Next">
                        <span aria-hidden="true"><i class="bi bi-chevron-right"></i></span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if search_term %}&search_term={{ search_term }}{% endif %}{% if searching_by %}&searching_by={{ searching_by }}{% endif %}" aria-label="Last">
                        <span aria-hidden="true"><i class="bi bi-chevron-double-right"></i></span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link" aria-hidden="true"><i class="bi bi-chevron-right"></i></span>
                </li>
                <li class="page-item disabled">
                    <span class="page-link" aria-hidden="true"><i class="bi bi-chevron-double-right"></i></span>
                </li>
            {% endif %}
        </ul>
    </div>
    
      
{% endblock %}

Achievement 2/Exercise2.8/src/apps/recipes/templates/recipes/recipe_charts.html
{% extends "base.html" %}
{% load markdownify %}
{% load recipe_filters %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block content %}
    <h1 class="display-3 mt-5 mb-4">Visualization</h1>
    <div class="row d-flex flex-column align-items-center">
        <div class="row justify-content-center border-bottom "> 
            <img class="img-fluid my-4 w-50" src="data:image/png;base64, {{bar_chart|safe}}">
        </div>
    
        <div class="row justify-content-center border-bottom"> 
            <img class="img-fluid my-4 w-50" src="data:image/png;base64, {{line_chart|safe}}">
        </div>
    
        <div class="row justify-content-center border-bottom"> 
            <img class="img-fluid my-4 w-50" src="data:image/png;base64, {{pie_chart|safe}}">
        </div>
    </div>
    
{% endblock %}

Achievement 2/Exercise2.8/src/apps/recipes/templates/recipes/recipe_detail.html
{% extends "base.html" %}
{% load markdownify %}
{% load recipe_filters %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block content %}

    <div class="row mt-5 pb-4 border-bottom"> 
    
        <div class="col-auto"> 
            <img src="{{ recipe.image.url }}" class="img-fluid rounded shadow" 
                 style="object-fit: cover; max-width: 400px;" alt="{{ recipe.name }}">
        </div>
      
        <div class="col ps-3"> 
            <h2 class="display-4">{{ recipe.name }}</h2>
            <div class="row">
                <div class="col-2">
                    <p class="mb-1 "><strong>Ingredients:</strong></p>
                </div>
                <div class="col">
                    <ul class=" ms-0 px-0">
                        {% for ingredient in recipe.ingredients|split_ingredients %}
                            <li class="list-group-item" >{{ ingredient }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-2">
                    <p><strong>Cooking Time:</strong></p>
                </div>
                <div class="col">
                    <p>{{ recipe.cooking_time }} minutes</p>
                </div>
            </div>
            <div class="row">
                <div class="col-2">
                    <p><strong>Difficulty:</strong> 
                </div>
                <div class="col">
                    <button type="button" class="btn {{ recipe.difficulty|style_difficulty }} disabled py-0 px-1">{{ recipe.difficulty }}</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row pt-3">
        <div class="col">
            <h3 class="display-6">Directions</h3>
            <p>{{ recipe.directions|markdownify }}</p>
        </div>
    </div>

{% endblock %}

Achievement 2/Exercise2.8/src/apps/recipes/templates/recipes/recipe_list.html
{% extends "base.html" %}
{% load recipe_filters %}
{% block title %}Recipes{% endblock %}

{% block content %}
    <h1 class="display-4 mt-5 mb-4">Recipes</h1>

    <div class="flex-grow-1">
        {% for recipe in recipes %}
        <div class="row py-3 border-bottom align-items-start">
            <div class="col-12 col-sm-4 col-md-3 pb-sm-0 pb-2">
                <a href="{% url 'recipe:recipe_detail' recipe.pk %}" >
                    <img src="{{ recipe.image.url }}" class="img-fluid rounded shadow w-100" alt="{{ recipe.name }}">
                </a>
            </div>
    
            <div class="col-12 col-sm px-sm-3 ">          
                <a href="{% url 'recipe:recipe_detail' recipe.pk %}" class="link-underline link-underline-opacity-0">
                    <h2 class="fs-2">{{ recipe.name }}</h2>
                </a>       
                <p class="my-2"><strong>Cooking Time:</strong> {{ recipe.cooking_time }} minutes</p>
                <p class="my-2"><strong>Difficulty:</strong> 
                    <button type="button" class="btn {{ recipe.difficulty|style_difficulty }} disabled py-0 px-1">{{ recipe.difficulty }}</button>
                </p>
            </div>
        </div>
        {% empty %}
            No recipes found.
        {% endfor %}
    </div>
    
{% endblock %}

<!-- Pagination -->
{% block pagination %}
    {% include 'recipes/pagination.html' %}
{% endblock %}

Achievement 2/Exercise2.8/src/apps/recipes/templates/recipes/search.html
{% extends "base.html" %}
{% load recipe_filters %}
{% block title %}Search{% endblock %}

{% block content %}
   
        <h2 class="mt-5 mb-4 display-4">Search Recipes</h2>
        
        <form method="post" class="row g-3">
            {% csrf_token %}
            
            <!-- Searching by: -->
            <div class="col-md-4">
                <select class="form-select" id="id_searching_by" name="searching_by">
                    {% for key, value in form.searching_by.field.choices %}
                        <option value="{{ key }}" {% if key == searching_by %}selected{% endif %}>{{ value }}</option>
                    {% endfor %}
                </select>
            </div>


            <!-- Search Term: -->
            <div class="col-md-6">
                <div class="input-group">
                    <input type="text" class="form-control" id="id_search_term" name="search_term" placeholder="Search for ..." value="{% if search_term %} {{search_term}} {% endif %}">
                    <button class="btn btn-outline-secondary" type="submit">
                        <i class="bi bi-search me-1"></i>  
                    </button>
                </div>
            </div>
        </form>

      <!-- Display search results -->
    
    {% if results %}
        <h2 class="display-6 mt-5 mb-4">Search Results</h2>
        {% for result in results %}
            <div class="row ms-2 py-3 border-bottom"> 
                <div class="col-auto"> 
                    <a href="{% url 'recipe:recipe_detail' result.id %}">
                        <img src="{{ result.image.url }}" class="img-fluid rounded shadow" 
                            style="object-fit: cover; height: 100%; max-width: 200px;" alt="{{ result.name }}">
                    </a>
                </div>

                <div class="col ps-3"> 
                    <a href="{% url 'recipe:recipe_detail' result.id %}" class="link-underline link-underline-opacity-0">
                        <h2 class="display-6">{{ result.name }}</h2>
                    </a>
                    <p><strong>Ingredients:</strong> {{ result.ingredients }}</p>
                    <p><strong>Cooking Time:</strong> {{ result.cooking_time }} minutes</p>
                    <p><strong>Difficulty:</strong> 
                        <button type="button" class="btn {{ result.difficulty|style_difficulty }} disabled py-0 px-1">{{ result.difficulty }}</button>
                    </p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p class="my-4 fs-3">No results found.</p>
    {% endif %}

    <h3 class=" mt-5">DataFrame Table</h3>
    {{df|safe}}
  
{% endblock %}

<!-- Pagination -->
{% block pagination %}
    {% include 'recipes/pagination.html' with page_obj=page_obj %}
{% endblock %}